### ISSUE TITLE
Missing import statement

### ISSUE THREAD

**Issue by AlexBuccheri** [HofstadterTools/HofstadterTools.github.io#3]
In `code/band_structure.py`

`import sys` is missing, which will cause the script to fail if logging is used:

```python
# initialize logger
if log:
   sys.stdout = sys.stderr = fu.Logger("band_structure", args)
```

**Comment by RMeli** [comment]
Related to https://github.com/openjournals/joss-reviews/issues/6356

**Comment by bartandrews** [comment]
Thank you for spotting this mistake. I have now added the sys import.
