### ISSUE TITLE
band_structure should safeguard against non-coprime nphi

### ISSUE THREAD

**Issue by katherineding** [HofstadterTools/HofstadterTools.github.io#4]
This is beyond the scope of the JOSS review, but I noticed this bug(?) so figured I might as well mention it here. 

I was testing out the `band_structure` command and saw that while 
`band_structure <...other flags...> -nphi 1 4` gives the correct plots,
`band_structure <...other flags...> -nphi 2 8` does not.

The code should probably raise an error for non-prime p/q, or do a GCD and convert any non-prime inputs to the coprime case.

**Comment by bartandrews** [comment]
Thank you for catching this! For consistency with the butterfly program, where non-coprime nphi are skipped, I now raise a ValueError when a non-coprime nphi is parsed to the band_structure program.

**Comment by RMeli** [comment]
Related to https://github.com/openjournals/joss-reviews/issues/6356
